version: "2"

services:
  orderer.evolve.co:
    container_name: orderer.evolve.co
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/evolve.co/orderers/orderer.evolve.co/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/evolve.co/orderers/orderer.evolve.co/tls/:/var/hyperledger/orderer/tls
      - orderer.evolve.co:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.evolve.co:
    container_name: peer0.org1.evolve.co
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.evolve.co
      - CORE_PEER_ADDRESS=peer0.org1.evolve.co:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.evolve.co:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.evolve.co:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org1.evolve.co/peers/peer0.org1.evolve.co/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org1.evolve.co/peers/peer0.org1.evolve.co/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.evolve.co:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.org1.evolve.co:
    container_name: peer1.org1.evolve.co
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.evolve.co
      - CORE_PEER_ADDRESS=peer1.org1.evolve.co:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.evolve.co:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.evolve.co:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org1.evolve.co/peers/peer1.org1.evolve.co/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org1.evolve.co/peers/peer1.org1.evolve.co/tls:/etc/hyperledger/fabric/tls
      - peer1.org1.evolve.co:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.org2.evolve.co:
    container_name: peer0.org2.evolve.co
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.evolve.co
      - CORE_PEER_ADDRESS=peer0.org2.evolve.co:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.evolve.co:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.evolve.co:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org2.evolve.co/peers/peer0.org2.evolve.co/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org2.evolve.co/peers/peer0.org2.evolve.co/tls:/etc/hyperledger/fabric/tls
      - peer0.org2.evolve.co:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.org2.evolve.co:
    container_name: peer1.org2.evolve.co
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.evolve.co
      - CORE_PEER_ADDRESS=peer1.org2.evolve.co:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.evolve.co:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.evolve.co:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org2.evolve.co/peers/peer1.org2.evolve.co/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org2.evolve.co/peers/peer1.org2.evolve.co/tls:/etc/hyperledger/fabric/tls
      - peer1.org2.evolve.co:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
