# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

volumes:
  ? orderer.evolve.co
  ? peer0.org1.evolve.co
  ? peer1.org1.evolve.co
  ? peer0.org2.evolve.co
  ? peer1.org2.evolve.co

networks:
  ? byfn

services:
  orderer.evolve.co:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.evolve.co
    container_name: orderer.evolve.co
    networks:
      - byfn

  peer0.org1.evolve.co:
    container_name: peer0.org1.evolve.co
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org1.evolve.co
    networks:
      - byfn

  peer1.org1.evolve.co:
    container_name: peer1.org1.evolve.co
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.org1.evolve.co
    networks:
      - byfn

  peer0.org2.evolve.co:
    container_name: peer0.org2.evolve.co
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org2.evolve.co
    networks:
      - byfn

  peer1.org2.evolve.co:
    container_name: peer1.org2.evolve.co
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.org2.evolve.co
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.evolve.co:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.evolve.co/peers/peer0.org1.evolve.co/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.evolve.co/peers/peer0.org1.evolve.co/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.evolve.co/peers/peer0.org1.evolve.co/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.evolve.co/users/Admin@org1.evolve.co/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.evolve.co
      - peer0.org1.evolve.co
      - peer1.org1.evolve.co
      - peer0.org2.evolve.co
      - peer1.org2.evolve.co
    networks:
      - byfn
