# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

volumes:
  ? orderer.evolve.co
  ? peer0.org1.evolve.co
  ? peer1.org1.evolve.co
  ? peer0.org2.evolve.co
  ? peer1.org2.evolve.co

networks:
  ? byfn
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.evolve.co-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.evolve.co-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.evolve.co/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.evolve.co-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.evolve.co-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.evolve.co/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn

  orderer.evolve.co:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.evolve.co
    container_name: orderer.evolve.co
    networks:
      - byfn

  peer0.org1.evolve.co:
    container_name: peer0.org1.evolve.co
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org1.evolve.co
    networks:
      - byfn

  peer1.org1.evolve.co:
    container_name: peer1.org1.evolve.co
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.org1.evolve.co
    networks:
      - byfn

  peer0.org2.evolve.co:
    container_name: peer0.org2.evolve.co
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org2.evolve.co
    networks:
      - byfn

  peer1.org2.evolve.co:
    container_name: peer1.org2.evolve.co
    extends:
      file: base/docker-compose-base.yaml
      service: peer1.org2.evolve.co
    networks:
      - byfn
